services:
  sonar:
    image: sonarqube:latest
    container_name: sonarqube-app
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true    
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_conf:/opt/sonarqube/conf  
    ports:
      - "9000:9000" 
    networks:
      - sonarnet
volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_conf:
  sonar_cache:           
networks:
  sonarnet:
    driver: bridge  